// Generated by gencpp from file iaocr_teleop/Angle.msg
// DO NOT EDIT!


#ifndef IAOCR_TELEOP_MESSAGE_ANGLE_H
#define IAOCR_TELEOP_MESSAGE_ANGLE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace iaocr_teleop
{
template <class ContainerAllocator>
struct Angle_
{
  typedef Angle_<ContainerAllocator> Type;

  Angle_()
    : data(0)  {
    }
  Angle_(const ContainerAllocator& _alloc)
    : data(0)  {
  (void)_alloc;
    }



   typedef uint16_t _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::iaocr_teleop::Angle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iaocr_teleop::Angle_<ContainerAllocator> const> ConstPtr;

}; // struct Angle_

typedef ::iaocr_teleop::Angle_<std::allocator<void> > Angle;

typedef boost::shared_ptr< ::iaocr_teleop::Angle > AnglePtr;
typedef boost::shared_ptr< ::iaocr_teleop::Angle const> AngleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::iaocr_teleop::Angle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::iaocr_teleop::Angle_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace iaocr_teleop

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'iaocr_teleop': ['/home/ubuntu/ROS_IAOCR/catkin_ws/src/iaocr_teleop/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::iaocr_teleop::Angle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iaocr_teleop::Angle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iaocr_teleop::Angle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iaocr_teleop::Angle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iaocr_teleop::Angle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iaocr_teleop::Angle_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::iaocr_teleop::Angle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1df79edf208b629fe6b81923a544552d";
  }

  static const char* value(const ::iaocr_teleop::Angle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1df79edf208b629fULL;
  static const uint64_t static_value2 = 0xe6b81923a544552dULL;
};

template<class ContainerAllocator>
struct DataType< ::iaocr_teleop::Angle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "iaocr_teleop/Angle";
  }

  static const char* value(const ::iaocr_teleop::Angle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::iaocr_teleop::Angle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16  data\n\
";
  }

  static const char* value(const ::iaocr_teleop::Angle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::iaocr_teleop::Angle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Angle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iaocr_teleop::Angle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::iaocr_teleop::Angle_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IAOCR_TELEOP_MESSAGE_ANGLE_H
