// Generated by gencpp from file IAOCR_heading_angle/Angle.msg
// DO NOT EDIT!


#ifndef IAOCR_HEADING_ANGLE_MESSAGE_ANGLE_H
#define IAOCR_HEADING_ANGLE_MESSAGE_ANGLE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace IAOCR_heading_angle
{
template <class ContainerAllocator>
struct Angle_
{
  typedef Angle_<ContainerAllocator> Type;

  Angle_()
    : angle(0)  {
    }
  Angle_(const ContainerAllocator& _alloc)
    : angle(0)  {
  (void)_alloc;
    }



   typedef uint8_t _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::IAOCR_heading_angle::Angle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::IAOCR_heading_angle::Angle_<ContainerAllocator> const> ConstPtr;

}; // struct Angle_

typedef ::IAOCR_heading_angle::Angle_<std::allocator<void> > Angle;

typedef boost::shared_ptr< ::IAOCR_heading_angle::Angle > AnglePtr;
typedef boost::shared_ptr< ::IAOCR_heading_angle::Angle const> AngleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::IAOCR_heading_angle::Angle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::IAOCR_heading_angle::Angle_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace IAOCR_heading_angle

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'IAOCR_heading_angle': ['/home/ubuntu/ROS_IAOCR/catkin_ws/src/IAOCR_heading_angle/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::IAOCR_heading_angle::Angle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::IAOCR_heading_angle::Angle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::IAOCR_heading_angle::Angle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::IAOCR_heading_angle::Angle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::IAOCR_heading_angle::Angle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::IAOCR_heading_angle::Angle_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::IAOCR_heading_angle::Angle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "70f18cf7713067edf3d007a4504b0aad";
  }

  static const char* value(const ::IAOCR_heading_angle::Angle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x70f18cf7713067edULL;
  static const uint64_t static_value2 = 0xf3d007a4504b0aadULL;
};

template<class ContainerAllocator>
struct DataType< ::IAOCR_heading_angle::Angle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "IAOCR_heading_angle/Angle";
  }

  static const char* value(const ::IAOCR_heading_angle::Angle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::IAOCR_heading_angle::Angle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 angle\n\
";
  }

  static const char* value(const ::IAOCR_heading_angle::Angle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::IAOCR_heading_angle::Angle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Angle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::IAOCR_heading_angle::Angle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::IAOCR_heading_angle::Angle_<ContainerAllocator>& v)
  {
    s << indent << "angle: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IAOCR_HEADING_ANGLE_MESSAGE_ANGLE_H
